"""add latitude and longitude to grievances

Revision ID: 5b1d05dab32d
Revises: b8eefcd57b72
Create Date: 2026-07-16 10:38:22.238049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1d05dab32d'
down_revision: Union[str, Sequence[str], None] = 'b8eefcd57b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grievances', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('grievances', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grievances', 'longitude')
    op.drop_column('grievances', 'latitude')
    # ### end Alembic commands ###
